# Generated by Django 2.0 on 2018-05-25 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=2)),
                ('efficency', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=255)),
                ('size', models.IntegerField(default=1)),
                ('cleanliness', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='EffectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('turns', models.IntegerField(default=2)),
                ('strength', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StatData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.FloatField(default=0)),
                ('traffic', models.FloatField(default=0)),
                ('crime', models.FloatField(default=0)),
                ('population', models.IntegerField(default=0)),
                ('money', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='game.AgentData')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='game.GameData')),
                ('stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='game.StatData')),
            ],
        ),
        migrations.CreateModel(
            name='TechData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schools', models.IntegerField(default=0)),
                ('curriculum', models.IntegerField(default=0)),
                ('roads', models.IntegerField(default=0)),
                ('infrastructure', models.IntegerField(default=0)),
                ('police_stations', models.IntegerField(default=0)),
                ('police_training', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='statedata',
            name='tech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='game.TechData'),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game.User'),
        ),
        migrations.AddField(
            model_name='effectdata',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='game.StateData'),
        ),
        migrations.AddField(
            model_name='buildingdata',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.LocationData'),
        ),
        migrations.AddField(
            model_name='buildingdata',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='game.StateData'),
        ),
        migrations.AddField(
            model_name='agentdata',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='game.GameData'),
        ),
        migrations.AddField(
            model_name='agentdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='game.User'),
        ),
    ]
