# Generated by Django 2.0 on 2018-05-25 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180525_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.IntegerField(default=1)),
                ('efficency', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=1)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.LocationData')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='game.StateData')),
            ],
        ),
    ]
