# Generated by Django 2.0 on 2018-05-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_statedata_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techdata',
            name='curriculum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='techdata',
            name='infrastructure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='techdata',
            name='police_stations',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='techdata',
            name='police_training',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='techdata',
            name='roads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='techdata',
            name='schools',
            field=models.IntegerField(default=0),
        ),
    ]
