# Generated by Django 2.0 on 2018-05-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20180522_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statdata',
            name='crime',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='statdata',
            name='education',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='statdata',
            name='money',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='statdata',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statdata',
            name='traffic',
            field=models.FloatField(default=0),
        ),
    ]
