# Generated by Django 2.0 on 2018-05-23 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20180522_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=2)),
                ('efficency', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='buildingdata',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.LocationData'),
        ),
        migrations.AddField(
            model_name='buildingdata',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='game.StateData'),
        ),
    ]
