# Generated by Django 2.0 on 2018-05-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20180523_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdata',
            name='size',
            field=models.IntegerField(default=1),
        ),
    ]
